"""last time active

Revision ID: 002df15a5696
Revises: f3a9a2988811
Create Date: 2021-04-29 23:01:28.101933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002df15a5696'
down_revision = 'f3a9a2988811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_time', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_time')
    # ### end Alembic commands ###
