"""Initial migration.

Revision ID: f3a9a2988811
Revises: d4a82cd58299
Create Date: 2021-04-29 16:51:33.119947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a9a2988811'
down_revision = 'd4a82cd58299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_time', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active_time')
    # ### end Alembic commands ###
